# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1934ae93c07380753213e760306c9779cb91145b2f864e56c6e120c806fe11012bcf4247e0cac5dfaee4de74b03359f85200125f1ebbdb2bce7f600d9ee38d22

test:
  secret_key_base: 1c5d4c75523f5607b30a1583cff32ee675123da461990aba60450c1fd380f02a94c3da4e927983aeed456bf8b758c2c6a5618a406ef25606652b2ce48660bab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
