# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcc2a3412c6df59d71bcb655f2bceea7498b71a6f28b53ed7388c0e71d16dabf8663e7180b015ddfb128780b037b5f09d35feffdd426858e9c1ccc78fc989455

test:
  secret_key_base: 6d92ff31eafdb971e71754919bf88ed63502d0b833389efb83563fa80a75eb39be52b86bffa826b10f27b764fbfabddc7ba7b2b9f06dff6a47027a05b11b9a05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
